### ISSUE TITLE
Add a predicate (css-expr?) to recognize valid css-exprs

### ISSUE THREAD

**Issue by jessealama** [leafac/css-expr#1]
I'd love to see a predicate that checks whether an arbitrary Racket value is a valid css-expr (that is, a value returned from `css-expr`). I'd like to use such a thing in contracts. Perhaps there's already such functionality and I'm overlooking it; but if not, I'd love to see that. Thanks for making such a great package!

**Comment by leafac** [comment]
Thank you for the kind words about `css-expr`.

The `css-expr` form serves not only to generate stylesheets, but also to generate fragments, for example, the `main-width` in [this example](https://docs.racket-lang.org/css-expr/index.html#%28form._%28%28lib._css-expr%2Fmain..rkt%29._css-expr%29%29). It would be impractical to check whether an arbitrary value can be an arbitrary `css-expr` fragment.

It’s possible, however, to check whether an arbitrary value is a complete stylesheet (something that could be passed to `css-expr->css` and wouldn’t raise an error):

```racket
(define (css-expr? expr)
  (with-handlers ([exn:fail:syntax? (λ (e) #f)])
    (parse expr)
    #t))

> (css-expr? (css-expr [body #:background-color black]))
#t
> (css-expr? (css-expr a-css-expr-fragment))
#f
```

Would this be useful to you?

**Comment by jessealama** [comment]
Hmm...for what I have in mind, I think that might be a bit too weak. But perhaps I'm misunderstanding something. Is it true that *every* S-expression composed of symbols (and which is a list) could have been generated by `css-expr`? Playing around, I find that I can generate pretty much whatever I want:

    (css-expr foo) ; ==> '(foo)
    (css-expr "foo") ; ==> '("foo")
    (css-expr #"hi") ; ==> '(#"hi")
    (css-expr hi there (you now (horton)) ; ==> '(hi there (you now (horton)))

The byte string example there is a bit surprising, but overall, these examples suggest to me that essentially any S-expression could be generated using `css-expr`. And that's reinforced when I read your solution using `parse`. Do I understand things correctly?

**Comment by leafac** [comment]
You understand correctly, the `css-expr` form can generate any S-expression because it’s just [another name for quasiquote](https://github.com/leafac/css-expr/blob/master/main.rkt#L1461). The `css-expr` form is intended to be flexible and capable of generating any fragment of a CSS-expression—it’s just a way for the programmer to communicate “this S-expression is a CSS-expression (or fragment thereof).”

**Comment by jessealama** [comment]
Thanks for clarifying -- I now see that my request is based on a misunderstanding of what `css-expr` does.
